### ISSUE TITLE
Allow indents

### ISSUE THREAD

**Issue by vlcty** [mmlb/yamlfmt#10]
I've a cosmetic issue :-)

Lists gets formatted like this:

```
hosts:
- item1
- item2
```

While it's valid YAML it doesn't look nice to me. I'd like to have it like this:

```
hosts:
  - azure.microsoft.com
  - login.live.com
```

I checked the manual to ruamel and it should work by adding something like this:

```
yaml.indent(mapping=2, sequence=4, offset=2)
```

That ends in an error

```
Traceback (most recent call last):
  File "/usr/local/bin/yamlfmt", line 56, in <module>
    sys.exit(main())
  File "/usr/local/bin/yamlfmt", line 49, in main
    round_trip(sout, sin)
  File "/usr/local/bin/yamlfmt", line 18, in round_trip
    yaml.indent(mapping=2, sequence=4, offset=2)
AttributeError: 'module' object has no attribute 'indent'
```

I'm not a python developer. My guess it has something to do with the older ruamel version. Can you confirm this? Or do you maybe have another idea?

**Comment by tchia04** [comment]
👍

**Comment by lyz-code** [comment]
Hi @vlcty , I've implemented your request in [yamlfix](https://lyz-code.github.io/yamlfix/), I'm currently [trying to merge](https://github.com/mmlb/yamlfmt/issues/17) both projects, but till then, you can use it.
