### ISSUE TITLE
Unable to redirect the output to a file

### ISSUE THREAD

**Issue by tchia04** [mmlb/yamlfmt#11]
I would like to redirect the output to a file so I can compare with the existing one to see what is the difference.  However I am not able to do that.  

$ python --version
Python 2.7.10

```$ yamlfmt test.yml > formatter.yml
Traceback (most recent call last):
  File "/Users/tchia/Library/Python/2.7/bin/yamlfmt", line 55, in <module>
    sys.exit(main())
  File "/Users/tchia/Library/Python/2.7/bin/yamlfmt", line 41, in main
    file_out = os.ttyname(sys.stdout.fileno())
OSError: [Errno 25] Inappropriate ioctl for device```

**Comment by mmlb** [comment]
I already don't like the complexity in file/arg/stdout handling and am not keen on making it worse, you can do this pretty easily yourself:
```sh
yamlfmt <t.yaml >tt.yaml
```

**Comment by garymm** [comment]
It's pretty surprising that simple output redirection doesn't work with this tool.

**Comment by mmlb** [comment]
use shell redirection

**Comment by CJKay** [comment]
This inability to redirect the output appears to make it impossible to use `yamlfmt` portably from within certain build systems (such as CMake).

**Comment by mmlb** [comment]
@CJKay CMake can't do `yamlfmt <in >out`?
