### ISSUE TITLE
question: Is the project still maintained?

### ISSUE THREAD

**Issue by lyz-code** [mmlb/yamlfmt#17]
Hi, I've seen that the pace of issue and pull request interaction has dropped in the last months. Are you still maintaining the project?

I've noticed the project lacks some features I love to see in a tool:

* Tests
* Documentation page
* CI pipeline
* Pre-commits
* [And several more...](https://lyz-code.github.io/cookiecutter-python-project/)

I have a [cookiecutter template](https://lyz-code.github.io/cookiecutter-python-project/) to generate python projects that adds all these features without any effort. So I've rewritten the program with tests in [this repository](https://github.com/lyz-code/yamlfix). 

Until you answer, I'm going to continue the development there. But if you agree, I can do a pull request to merge both projects.

**Comment by mmlb** [comment]
yamlfmt has long been unmaintained, checkout https://github.com/lyz-code/yamlfix or https://github.com/prettier/prettier for alternatives.
