### ISSUE TITLE
This is *nix only -fcmod problems

### ISSUE THREAD

**Issue by matthewdeanmartin** [mmlb/yamlfmt#18]
formatting strings doesn't seem like something that should be tightly tied to the operating system.

```
$ yamlfmt *.yaml -w
Traceback (most recent call last):
  File "C:\Users\matth\.virtualenvs\search_service-3Tw2H1cF\Scripts\yamlfmt", line 55, in <module>
    sys.exit(main())
  File "C:\Users\matth\.virtualenvs\search_service-3Tw2H1cF\Scripts\yamlfmt", line 45, in main
    file_out = make_temp_file(file)
  File "C:\Users\matth\.virtualenvs\search_service-3Tw2H1cF\Scripts\yamlfmt", line 26, in make_temp_file
    os.fchmod(fd, stat.st_mode)
AttributeError: module 'os' has no attribute 'fchmod'
```

If there is a maintainer here, let know & I'll create a PR.

**Comment by mmlb** [comment]
Hey @matthewdeanmartin I will agree, but I'm not really using this tool anymore⁰ and do not wish to invest time into it. I'm not sure how to copy the file permissions, but will accept a PR if you wish to submit.

⁰: I've been very happy with github.com/prettier/prettier

**Comment by matthewdeanmartin** [comment]
Sonar doesn't like prettier.

If you'd be willing to invest the time to add me as another maintainer to the project, that' be great.

In the meanwhile here is a PR:
https://github.com/mmlb/yamlfmt/pull/19

**Comment by mmlb** [comment]
yamlfmt has long been unmaintained, checkout https://github.com/lyz-code/yamlfix or https://github.com/prettier/prettier for alternatives.
