### ISSUE TITLE
yamlfix "optimizes" strings to boolean

### ISSUE THREAD

**Issue by schorsch3000** [mmlb/yamlfmt#21]
see:
```
echo "foo: 'n'" | yamlfix  -
[+] Fixing files:
  - <stdin>
---
foo: n
[+] Done.
```

The string `n` represented as `'n'` is converted into a literal `n` which according to https://yaml.org/type/bool.html is a boolean `false`
The same goes for N, Y and y, all other boolean representation are kept qouted

**Comment by mmlb** [comment]
yamlfmt has long been unmaintained, checkout https://github.com/lyz-code/yamlfix or https://github.com/prettier/prettier for alternatives.
